# Generated by Django 3.2.10 on 2023-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedb',
            fields=[
                ('Course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Institution', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact', models.IntegerField(blank=True, null=True)),
                ('Duration', models.CharField(blank=True, max_length=100, null=True)),
                ('Fees', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
