# Generated by Django 3.2.10 on 2023-09-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_jobcategorydb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcategorydb',
            old_name='Name',
            new_name='Industry',
        ),
    ]
