# Generated by Django 3.2.10 on 2023-09-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_rename_name_jobcategorydb_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdb',
            name='Industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
