# Generated by Django 3.2.10 on 2023-09-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_coursecetogory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseCetogory',
            new_name='CourseCetogorydb',
        ),
    ]
