# Generated by Django 3.2.10 on 2023-09-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_rename_coursecetogory_coursecetogorydb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdb',
            old_name='Name',
            new_name='Job_Name',
        ),
    ]
