# Generated by Django 3.2.10 on 2023-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdb',
            name='Job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
