# Generated by Django 3.2.10 on 2023-09-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_applicationdb_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
