# Generated by Django 3.2.10 on 2023-09-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_applicationdb_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdb',
            name='Name',
        ),
    ]
