# Generated by Django 3.2.10 on 2023-09-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_remove_applicationdb_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdb',
            old_name='Job_id',
            new_name='Japp_id',
        ),
    ]
