# Generated by Django 3.2.10 on 2023-09-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_rename_job_id_applicationdb_japp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdb',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume'),
        ),
    ]
